/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentaApp.java
 *
 * Created on 09/11/2012, 02:18:20 PM
 */
package com.app;

import com.entidades.Articulo;
import com.entidades.Cliente;
import com.entidades.Funcionario;
import com.entidades.Tipo;
import com.entidades.VentaCab;
import com.entidades.VentaDet;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import util.HibernateUtil;

/**
 *
 * @author Geek
 */
public class VentaApp extends javax.swing.JDialog {

    /** Creates new form VentaApp */
    public static boolean pagada=true;
    public VentaApp(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        hibernateSession();
        arranque();
        nuevo();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.jPanel4.setEnabled(false);
        this.idArt.setVisible(false);
        this.fecha.setVisible(false);
        this.id.setVisible(false);
        this.idClie.setVisible(false);
        this.desArt1.setVisible(false);
        jRadioButton3.setSelected(true);
        pagada=true;
        

    }
    
    static Principal prin = new Principal();
    private DefaultTableModel model;
    private Session st;
    private int var,idArtt,numVenta;
   // List<Articulo>  lista = (List<Articulo>)st.createQuery("From Articulo").list();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        fecha = new javax.swing.JTextField();
        idArt = new javax.swing.JTextField();
        idClie = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        desArt1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        totalGeneral = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        eliminar = new org.edisoncor.gui.button.ButtonSeven();
        agregar = new org.edisoncor.gui.button.ButtonSeven();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pve = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        producto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas");
        setModal(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        fecha.setEditable(false);
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 100, -1));

        idArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idArtKeyPressed(evt);
            }
        });
        jPanel1.add(idArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 16));

        idClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idClieKeyPressed(evt);
            }
        });
        jPanel1.add(idClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 22, 16));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Ventas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Realize las ventas del dia...");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 770, 10));

        desArt1.setEditable(false);
        jPanel1.add(desArt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 24, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nuevo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New-file-icon-3.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nuevo.setContentAreaFilled(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save-icon.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        guardar.setContentAreaFilled(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/delete-file-icon.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.setContentAreaFilled(false);
        cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        totalGeneral.setEditable(false);
        totalGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalGeneral.setForeground(new java.awt.Color(0, 0, 102));
        totalGeneral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGeneralActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setText("Total esta venta:");

        jLabel18.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel18.setText("Q.");

        jLabel1.setFont(new java.awt.Font("Comfortaa", 3, 12)); // NOI18N
        jLabel1.setText("Esc para salir. . .");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel25)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 540, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setText("Eliminar");
        eliminar.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(0, 204, 0));
        agregar.setText("Agregar");
        agregar.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Precio Venta", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Articulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comfortaa", 1, 13))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Descripcion");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Precio de Venta:");

        pve.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Existencias:");

        can.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Cantidad:");

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Total:");

        total.setEditable(false);

        producto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar producto" }));
        producto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        producto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productoItemStateChanged(evt);
            }
        });
        producto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productoFocusLost(evt);
            }
        });
        producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel7.setText("Q.");

        jLabel10.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel10.setText("Q.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(producto, 0, 316, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pve, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(48, 48, 48)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comfortaa", 1, 12))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Número de orden:");

        num.setEditable(false);
        num.setForeground(new java.awt.Color(0, 51, 153));
        num.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Hora:");

        hora.setEditable(false);
        hora.setForeground(new java.awt.Color(0, 51, 153));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 830, 310));

        jRadioButton3.setFont(new java.awt.Font("Comfortaa", 3, 12)); // NOI18N
        jRadioButton3.setText("¿Venta Pagada?");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();// Evento ActionPerformed para botón nuevo.
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        arranque();// Evento ActionPerformed para botón cancelar.
    }//GEN-LAST:event_cancelarActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "id".
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            buscarFuncionario();
        }
    }//GEN-LAST:event_idKeyPressed

    private void idClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClieKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idClie".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarCliente();
        }
    }//GEN-LAST:event_idClieKeyPressed

    private void idArtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idArtKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idArt".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarArticulo();
        }
    }//GEN-LAST:event_idArtKeyPressed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "cantidad".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            calcularParcial();
        }
    }//GEN-LAST:event_cantidadKeyPressed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();// Evento ActionPerformed para botón guardar.
//        prin.arranque();
//        prin.centrar();
    }//GEN-LAST:event_guardarActionPerformed

    
    private void totalGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalGeneralActionPerformed

    private void productoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productoItemStateChanged
        // TODO add your handling code here:
        if(producto.getSelectedIndex()>0){
           buscarArticulocom();
        }
        else{
        this.desArt1.setText(null);
        this.pve.setText((null));
        this.can.setText((null));
        this.cantidad.setText(null);
        this.idArt.setText(null);
        }
        
    }//GEN-LAST:event_productoItemStateChanged

    private void productoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productoFocusLost
        // TODO add your handling code here:
       
        
        
        
    }//GEN-LAST:event_productoFocusLost

    private void productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoKeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_productoKeyPressed

    private void productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoKeyTyped
        // TODO add your handling code here:
         producto.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,
                java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            System.out.println("SIEMPRE");
            buscarArticulocom();
        }
       
    }//GEN-LAST:event_productoKeyTyped

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        agregar();// Evento ActionPerformed para botón agregar.
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();// Evento ActionPerformed para botón eliminar.
    }//GEN-LAST:event_eliminarActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()== true) {
            pagada=true;
        }else{
            pagada=false;
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    DefaultComboBoxModel combomodel;

    private void addEscapeKey(){
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction(){
           @Override
           public void actionPerformed(ActionEvent e){
               dispose();
           }      
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }
    public void cargarCombo(){
        
    hibernateSession();
    combomodel=(DefaultComboBoxModel) producto.getModel();
    combomodel.removeAllElements();
    combomodel.addElement("Selecione un producto");
    List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo a order by a.des").list();
    for(Articulo tipoList : lista){
        combomodel.addElement(tipoList);            
    }
    System.out.println(""+combomodel.getSize());
    producto.setModel(combomodel);
}
    public void guardar2(){
       st.beginTransaction();
       Cliente clie = new Cliente();
       clie.setDes("c/f");
       clie.setDir("Direccion");
       clie.setTel("77777777");
       clie.setRuc("c/f");
       st.save(clie);
       st.getTransaction().commit();
       JOptionPane.showMessageDialog(null, "Registro de cliente guardado.");
       cargarDatos();
       this.producto.requestFocus();
      
    }
    public void cargarDatos(){
    st.beginTransaction();
    List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();
    for(Cliente clie : lista){       
        this.idClie.setText("1");
        
    }
    
    
    
    
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                VentaApp dialog = new VentaApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        prin.arranque();
//                        prin.centrar();
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven agregar;
    private javax.swing.JTextField can;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField desArt1;
    private org.edisoncor.gui.button.ButtonSeven eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField hora;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idArt;
    private javax.swing.JTextField idClie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox producto;
    private javax.swing.JTextField pve;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalGeneral;
    // End of variables declaration//GEN-END:variables
public void hibernateSession(){
    st = HibernateUtil.getSessionFactory().openSession();
}
public void arranque(){
    //AutoCompleteDecorator.decorate(this.producto);
    addEscapeKey();
    cargarCombo();
    this.jPanel4.setEnabled(false);
    this.id.setEnabled(false);
    this.nuevo.setEnabled(true);
    this.agregar.setEnabled(false);
    this.eliminar.setEnabled(false);
    this.guardar.setEnabled(false);
    this.num.setText(null);
    this.fecha.setText(null);
    this.hora.setText(null);
    this.id.setText(null);
    this.id.setEnabled(false);
//    this.nombres.setText(null);
//    this.apellidos.setText(null);
    this.idClie.setText(null);
    this.idClie.setEnabled(false);
//    this.des.setText(null);
    this.idArt.setText(null);
    this.idArt.setEnabled(false);
    this.fecha.setText(null);
    this.pve.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.cantidad.setEnabled(false);
    this.total.setText(null);
    this.totalGeneral.setText(null);
    this.id.setText("1");
    Calendar cal = Calendar.getInstance();
    String calString = retornarString(cal);
    this.fecha.setText(calString);
//    this.nombres.setText("Dr. Eular");
//    this.apellidos.setText("Bautista");
//    this.des.setText(null);
//    this.ruc.setText(null);
    AutoCompleteDecorator.decorate(this.producto);
    tableModel();
}
public void tableModel(){
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
    this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}
public void nuevo(){
    obtenetID();
    this.id.setText("1");
//    this.nombres.setText("Dr. Eular");
//    this.apellidos.setText("Bautista");
    this.jPanel4.setEnabled(true);
    this.id.setEnabled(false);
    this.idClie.setEnabled(true);
//    this.des.setEditable(true);
//    this.ruc.setEditable(true);
    this.idArt.setEnabled(true);
    this.cantidad.setEnabled(true);
    this.agregar.setEnabled(true);
    this.eliminar.setEnabled(true);
    this.guardar.setEnabled(true);
    this.nuevo.setEnabled(false);
    this.id.requestFocus();
    Calendar cal = Calendar.getInstance();
    String calString = retornarString(cal);
    String calHora = retornarStringHora(cal);
    this.fecha.setText(calString);
    this.num.setText(String.valueOf(numVenta));    
    this.hora.setText(calHora);
    this.id.setText("1");
//    this.nombres.setText("Dr. Eular");
//    this.apellidos.setText("Bautista");
}
public void obtenetID(){
    numVenta = 0;
    List<VentaCab> lista = (List<VentaCab>)st.createQuery("From VentaCab").list();
    for (Iterator<VentaCab> it = lista.iterator(); it.hasNext();) {
        VentaCab ventaCab = it.next();
        numVenta = ventaCab.getNum() + 1;
    }
    if(numVenta==0){
        numVenta=1;
    } 
}
public void buscarArticulo(){
    int idArti = 0;
    try {
        try {
           idArti = Integer.parseInt(this.idArt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
        Articulo art = (Articulo)st.load(Articulo.class, idArti);
        this.desArt1.setText(art.getDes());
        this.pve.setText(String.valueOf(art.getPve()));
        this.can.setText(String.valueOf(art.getCan()));
        this.cantidad.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay artículo con ID: " + idArti);
    }    
}

public void buscarArticulocom(){
    int idArti = 0;
    try {
        try {
           idArti =((Articulo)producto.getSelectedItem()).getId();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
        Articulo art = (Articulo)st.load(Articulo.class, idArti);
        this.desArt1.setText(art.getDes());
        this.pve.setText(String.valueOf(art.getPve()));
        this.can.setText(String.valueOf(art.getCan()));
        this.cantidad.requestFocus();
        this.idArt.setText(""+idArti);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay artículo con ID: " + idArti);
    }    
}




public void calcularParcial(){
    int canVent = 0;
    double pVenta = 0;
    int stock = 0;
    double totalParcial = 0 ;
    try {
        canVent = Integer.parseInt(this.cantidad.getText());
        pVenta = Double.parseDouble(this.pve.getText());
        stock = Integer.parseInt(this.can.getText());
        if(stock < canVent){
             JOptionPane.showMessageDialog(null, "Stock insuficiente.");
        }
        else{
           totalParcial = canVent * pVenta;
           totalParcial = Math.rint(totalParcial*100)/100;
           this.total.setText(String.valueOf(totalParcial)); 
           this.agregar.requestFocus();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Se requiere datos numérico.");
    }
}
public void buscarFuncionario(){
    int idFunc = 0;
    try {
        try {
           idFunc = Integer.parseInt(this.id.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
//         Funcionario funcio = (Funcionario)st.load(Funcionario.class, idFunc);
//         this.nombres.setText(funcio.getNombres());
//         this.apellidos.setText(funcio.getApellidos());
         this.idClie.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay funcionario con ID: " + idFunc);
    }    
}
public void buscarCliente(){
    int idCl = 0;
    try {
        try {
           idCl = Integer.parseInt(this.idClie.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
         Cliente clie = (Cliente)st.load(Cliente.class, idCl);
//         this.des.setText(clie.getDes());
//         this.ruc.setText(clie.getRuc());
         this.idArt.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay cliente con ID: " + idCl);
    }    
}
public void buscarClienteNombre(String nombre){
   
    
    List<Cliente> lista = (List<Cliente>)st.createQuery("a From Cliente where a.des ="+nombre+"").list();
    for(Cliente tipoList : lista){
//        this.des.setText(tipoList.getDes());
//        this.ruc.setText(tipoList.getRuc());
        this.idClie.setText(String.valueOf(tipoList.getId()));
        
    }   
    cargarDatos();
}

public void agregar(){
    if(this.id.getText().isEmpty()){
        //JOptionPane.showMessageDialog(null, "Seleccione un funcionario.");
        this.id.setText("0");
    }
    else{
            if(this.idArt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Seleccione un articulo.");
            }
            else{
                if(this.cantidad.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Indique una cantidad.");
                }
                else{
                    verificar();
                    if(var>=1){
                        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Artículo ya Agregado. Desea sumar la cantidad.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
                        if(showConfirmDialog==0){
                           sumarRepetido(); 
                           calcular();
                           confimAgregar();
                           limpiar();
                        }
                        else{
                            limpiar();
                            this.idArt.requestFocus();
                        }
                    }
                    else{
                            model.addRow(new Object[]{
                            this.idArt.getText(),this.desArt1.getText(),this.pve.getText(),this.cantidad.getText(),this.total.getText()
                            });                    
                            calcular();
                            confimAgregar();
                            limpiar(); 
                    }
                    
                }
            }
        
    }
}
public void confimAgregar(){
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Agregar más Articulos.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            this.producto.requestFocus();
        }
        else{
            this.guardar.requestFocus();
        }
        
}
public void limpiar(){
    this.idArt.setText(null);
    this.fecha.setText(null);
    this.pve.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.total.setText(null);
    this.id.setEnabled(false);
    this.idClie.setEnabled(false);
    
}
public void calcular(){
    double totalG = 0;
    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
        Object valueAt = model.getValueAt(i, 4);
        totalG += Double.parseDouble(valueAt.toString());
    }
    this.totalGeneral.setText(String.valueOf(totalG));
}
public void verificar(){
    var = 0;
    int idAr = Integer.parseInt(this.idArt.getText());
    if(this.jTable1.getRowCount()>=1){
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
        Object valueAt = model.getValueAt(i, 0);
        int parseInt = Integer.parseInt(valueAt.toString());
        if(idAr == parseInt){
            var = 1;
            idArtt = i;
        }        
        }        
    }  
}
public void sumarRepetido(){
        int artCant = Integer.parseInt(this.cantidad.getText());
        double artTotal = Double.parseDouble(this.total.getText());
        Object valueAt = model.getValueAt(idArtt, 3);
        Object valueAt1 = model.getValueAt(idArtt, 4);
        int cantArt = Integer.parseInt(valueAt.toString());
        double totalArt = Double.parseDouble(valueAt1.toString());
        int x = artCant + cantArt;
        double y = artTotal + totalArt;
        int t = Integer.parseInt(this.can.getText());
        if(t>=x){
            model.setValueAt(x, idArtt, 3);
            model.setValueAt(y, idArtt, 4);
        }
        else{
           JOptionPane.showMessageDialog(null, "Stock de artículos insuficiente."); 
        }
        
}

public String retornarString(Calendar fecha){
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}
public String retornarStringHora(Calendar fecha){
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}    
public Calendar retornarCalendar(String fecha){
        SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
        Calendar cal = Calendar.getInstance();    
        try {
            cal.setTime(sdf.parse(fecha));
        } catch (ParseException ex) {
          
        }
        return cal;
    }
public void eliminar(){
    if(this.jTable1.getSelectedRow()==-1){
      JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila de la tabla.");  
    }
    else{
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminar fila seleccionada.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            int sel = this.jTable1.getSelectedRow();
            model.removeRow(sel);
            this.idArt.requestFocus();
        }
        else{
            this.idArt.requestFocus();
        }
    }
}

public void guardar(){
    this.id.setText("1");
    this.idClie.setText("1");
    if(this.id.getText().isEmpty() ||this.idClie.getText().isEmpty() ){
        JOptionPane.showMessageDialog(null, "Faltan datos para guardar. Verifique.");
    }
    else{
        if(this.jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No hay datos para guardar.");
        }
        else{
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Desea guardar esta venta.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog == 0){
                try {
                    st.beginTransaction();
                    VentaCab venta = new VentaCab();
                    int idFun = 1;
                    int idCli = 1;
                    double totalVenta = Double.parseDouble(this.totalGeneral.getText());
                    Funcionario funcionario = (Funcionario)st.load(Funcionario.class, idFun);
                    Cliente cliente = (Cliente)st.load(Cliente.class, idCli);
                    Calendar fechaVenta = retornarCalendar(this.fecha.getText());
                    String horaVenta = this.hora.getText();
                    venta.setPagado(pagada);
                    venta.setCliente(cliente);
                    venta.setFuncionario(funcionario);
                    venta.setFecha(fechaVenta);
                    venta.setHora(horaVenta);
                    venta.setTotal(totalVenta);
                    funcionario.getVentaCabs().add(venta);
                    cliente.getVentaCabs().add(venta);
                    int rowCount = this.jTable1.getRowCount();
                    int[] idArti = new int[rowCount];
                    int[] cantVenta = new int[rowCount];
                    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
                        VentaDet detalleVenta = new VentaDet();
                        int idArticulo = Integer.parseInt(String.valueOf(model.getValueAt(i, 0)));
                        idArti[i] = idArticulo;
                        Articulo ventaArticulo = (Articulo)st.load(Articulo.class, idArticulo);
                        int cantidadVenta = Integer.parseInt(String.valueOf(model.getValueAt(i, 3)));
                        cantVenta[i]= cantidadVenta;
                        double importeVenta = Double.parseDouble(String.valueOf(model.getValueAt(i, 4)));
                        detalleVenta.setArticulo(ventaArticulo);
                        detalleVenta.setCant(cantidadVenta);
                        detalleVenta.setImporte(importeVenta);
                        detalleVenta.setVentaCab(venta);
                        venta.getVentaDets().add(detalleVenta);
                    }
                    st.save(venta);
                    st.getTransaction().commit();
                    for (int i = 0; i < idArti.length; i++) {
                        actualizarStrock(cantVenta[i], idArti[i]);
                    }
                    arranque();
                    JOptionPane.showMessageDialog(null, "Venta guardada correctamente.");
                    this.dispose();
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error guardando venta. Verifique.");
                }
                
            }
            else{                
                this.idArt.requestFocus();
            }
            
        }
    }
}
public void actualizarStrock(int cantidadVendida, int idArticulo){
    st.beginTransaction();
    Articulo actualizar = (Articulo)st.load(Articulo.class, idArticulo);
    int temp = actualizar.getCan() - cantidadVendida;
    actualizar.setCan(temp);
    st.update(actualizar);
    st.getTransaction().commit();
}
}
